import {
  app,
  BrowserWindow,
  dialog,
  ipcMain,
  nativeTheme,
  type OpenDialogOptions,
} from "electron";
import started from "electron-squirrel-startup";
import { randomUUID } from "node:crypto";
import path from "node:path";
import { z } from "zod";
import { ProjectRuntimeRegistry } from "./main/projectRuntime";
import { ProjectRepository } from "./main/projects/projectRepository";
import {
  CREATE_PROJECT_CHANNEL,
  CLOSE_PROJECT_CHANNEL,
  DELETE_PROJECT_CHANNEL,
  LIST_PROJECTS_CHANNEL,
  OPEN_PROJECT_CHANNEL,
  PICK_PROJECT_FOLDERS_CHANNEL,
  PROJECTS_DIRECTORY,
  UPDATE_PROJECT_CHANNEL,
  type DeleteProjectResult,
  type ListProjectsResult,
  type PickProjectFoldersResult,
  type ProjectResult,
} from "./shared/projects";
import {
  RESUME_SESSION_CHANNEL,
  SEARCH_SESSIONS_CHANNEL,
  type ResumeSessionResult,
  type SearchSessionsResult,
} from "./shared/sessions";
import {
  LIST_PROJECT_DIRECTORY_CHANNEL,
  type ListProjectDirectoryResult,
} from "./shared/projectFiles";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (started) {
  app.quit();
}

nativeTheme.themeSource = "system";

const projectRuntimes = new ProjectRuntimeRegistry();
let projectRepository: ProjectRepository | null = null;

const ProjectFolderInputSchema = z.object({
  access: z.enum(["read-only", "read-write"]),
  id: z.uuid(),
  name: z.string().trim().min(1).max(100),
  path: z.string().min(1).max(4_096),
});
const ProjectMutationSchema = z
  .object({
    defaultFolderId: z.uuid(),
    folders: z.array(ProjectFolderInputSchema).min(1),
    name: z.string().trim().min(1).max(100),
  })
  .superRefine((project, context) => {
    const defaultFolder = project.folders.find(
      (folder) => folder.id === project.defaultFolderId,
    );
    if (defaultFolder?.access === "read-write") return;

    context.addIssue({
      code: "custom",
      message: "The default folder must have read-write access.",
      path: ["defaultFolderId"],
    });
  });
const PickProjectFoldersRequestSchema = z.object({
  mode: z.enum(["context", "default"]),
});
const ProjectIdRequestSchema = z.object({ id: z.uuid() });
const UpdateProjectRequestSchema = ProjectMutationSchema.safeExtend({
  id: z.uuid(),
});
const SearchSessionsRequestSchema = z.object({
  query: z.string().max(500),
});
const ResumeSessionRequestSchema = z.object({
  sessionId: z.uuid(),
});
const ListProjectDirectoryRequestSchema = z.object({
  folderId: z.uuid(),
  relativePath: z.string().max(4_096),
});

function getProjectRepository(): ProjectRepository {
  if (!projectRepository) throw new Error("Project storage is not ready.");
  return projectRepository;
}

const createWindow = () => {
  const mainWindow = new BrowserWindow({
    title: "Pine",
    titleBarStyle: "hidden",
    ...(process.platform === "darwin"
      ? { trafficLightPosition: { x: 21, y: 21 } }
      : { titleBarOverlay: true }),
    width: 1120,
    height: 760,
    minWidth: 720,
    minHeight: 540,
    show: false,
    autoHideMenuBar: process.platform !== "darwin",
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
      preload: path.join(__dirname, "preload.js"),
    },
  });
  const webContentsId = mainWindow.webContents.id;

  mainWindow.once("ready-to-show", () => {
    mainWindow.show();
  });
  mainWindow.webContents.once("destroyed", () => {
    void projectRuntimes.dispose(webContentsId);
  });
  mainWindow.webContents.setWindowOpenHandler(() => ({ action: "deny" }));

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    void mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    void mainWindow.loadFile(
      path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`),
    );
  }

  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.webContents.openDevTools();
  }
};

ipcMain.handle(
  LIST_PROJECTS_CHANNEL,
  async (): Promise<ListProjectsResult> => ({
    projects: await getProjectRepository().list(),
  }),
);

ipcMain.handle(
  PICK_PROJECT_FOLDERS_CHANNEL,
  async (event, request: unknown): Promise<PickProjectFoldersResult> => {
    const { mode } = PickProjectFoldersRequestSchema.parse(request);
    const parentWindow = BrowserWindow.fromWebContents(event.sender);
    const options: OpenDialogOptions = {
      title:
        mode === "default" ? "Choose Default Folder" : "Add Context Folders",
      buttonLabel: mode === "default" ? "Choose" : "Add",
      properties: [
        "openDirectory",
        ...(mode === "context" ? (["multiSelections"] as const) : []),
        "createDirectory",
        "promptToCreate",
      ],
    };
    const selection = parentWindow
      ? await dialog.showOpenDialog(parentWindow, options)
      : await dialog.showOpenDialog(options);

    if (selection.canceled) return { folders: [] };
    return {
      folders: selection.filePaths.map((folderPath) => ({
        access: "read-write",
        id: randomUUID(),
        name: path.basename(folderPath),
        path: folderPath,
      })),
    };
  },
);

ipcMain.handle(
  CREATE_PROJECT_CHANNEL,
  async (_event, request: unknown): Promise<ProjectResult> => ({
    project: await getProjectRepository().create(
      ProjectMutationSchema.parse(request),
    ),
  }),
);

ipcMain.handle(CLOSE_PROJECT_CHANNEL, async (event): Promise<void> => {
  await projectRuntimes.dispose(event.sender.id);
});

ipcMain.handle(
  OPEN_PROJECT_CHANNEL,
  async (event, request: unknown): Promise<ProjectResult> => {
    const { id } = ProjectIdRequestSchema.parse(request);
    const repository = getProjectRepository();
    const project = await repository.open(id);
    await projectRuntimes.open(
      event.sender.id,
      project,
      repository.dataPaths(id),
    );
    return { project };
  },
);

ipcMain.handle(
  UPDATE_PROJECT_CHANNEL,
  async (event, request: unknown): Promise<ProjectResult> => {
    const { id, ...input } = UpdateProjectRequestSchema.parse(request);
    const repository = getProjectRepository();
    const project = await repository.update(id, input);
    if (projectRuntimes.isOpen(event.sender.id, id)) {
      await projectRuntimes.open(
        event.sender.id,
        project,
        repository.dataPaths(id),
      );
    }
    return { project };
  },
);

ipcMain.handle(
  DELETE_PROJECT_CHANNEL,
  async (event, request: unknown): Promise<DeleteProjectResult> => {
    const { id } = ProjectIdRequestSchema.parse(request);
    if (projectRuntimes.isOpen(event.sender.id, id)) {
      await projectRuntimes.dispose(event.sender.id);
    }
    return { deleted: await getProjectRepository().delete(id) };
  },
);

ipcMain.handle(
  LIST_PROJECT_DIRECTORY_CHANNEL,
  async (event, request: unknown): Promise<ListProjectDirectoryResult> => {
    const { folderId, relativePath } =
      ListProjectDirectoryRequestSchema.parse(request);
    return {
      entries: await projectRuntimes.listDirectory(
        event.sender.id,
        folderId,
        relativePath,
      ),
    };
  },
);

ipcMain.handle(
  SEARCH_SESSIONS_CHANNEL,
  async (event, request: unknown): Promise<SearchSessionsResult> => {
    const { query } = SearchSessionsRequestSchema.parse(request);
    return {
      sessions: await projectRuntimes.search(event.sender.id, query),
    };
  },
);

ipcMain.handle(
  RESUME_SESSION_CHANNEL,
  async (event, request: unknown): Promise<ResumeSessionResult> => {
    const { sessionId } = ResumeSessionRequestSchema.parse(request);
    return {
      session: await projectRuntimes.resume(event.sender.id, sessionId),
    };
  },
);

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  projectRepository = new ProjectRepository(
    path.join(app.getPath("userData"), PROJECTS_DIRECTORY),
  );
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
