import {
  ProjectFileOperationSchema,
  ProjectEntryReferenceSchema,
} from "./main/projectFileOperations";
import {
  app,
  BrowserWindow,
  clipboard,
  dialog,
  ipcMain,
  nativeTheme,
  protocol,
  shell,
  webContents,
  type OpenDialogOptions,
} from "electron";
import started from "electron-squirrel-startup";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { ProjectRuntimeRegistry } from "./main/projectRuntime";
import {
  readProjectFilePreview,
  serveProjectMedia,
} from "./main/projectFilePreview";
import { installWindowShortcuts } from "./main/windowShortcuts";
import { AgentProcessHost } from "./main/agentProcessHost";
import { ModelRecommendationService } from "./main/modelRecommendations";
import { ProjectRepository } from "./main/projects/projectRepository";
import {
  ABORT_SESSION_CHANNEL,
  APPROVAL_RESPONSE_CHANNEL,
  PROMPT_SESSION_CHANNEL,
  SET_APPROVAL_MODE_CHANNEL,
  SESSION_EVENT_CHANNEL,
  type AbortSessionResult,
  type PromptSessionResult,
  type RespondApprovalRequest,
  type SetApprovalModeResult,
} from "./shared/agent";
import {
  ATTACHMENT_IMAGE_PROTOCOL,
  INSPECT_ATTACHMENTS_CHANNEL,
  MAX_PASTED_IMAGE_BYTES,
  OPEN_ATTACHMENT_CHANNEL,
  PICK_ATTACHMENT_FOLDERS_CHANNEL,
  PICK_ATTACHMENTS_CHANNEL,
  SAVE_PASTED_ATTACHMENT_CHANNEL,
  extensionForPastedImage,
  PASTED_IMAGE_MIME_TYPES,
  type PineAttachment,
  type PineAttachmentKind,
  type OpenAttachmentResult,
  type PickAttachmentsResult,
  type SavePastedAttachmentResult,
} from "./shared/attachments";
import {
  CANCEL_PROVIDER_AUTH_CHANNEL,
  GET_MODEL_CATALOG_CHANNEL,
  LOGIN_PROVIDER_CHANNEL,
  LOGOUT_PROVIDER_CHANNEL,
  OPEN_PROVIDER_AUTH_URL_CHANNEL,
  PROVIDER_AUTH_EVENT_CHANNEL,
  RESPOND_PROVIDER_AUTH_CHANNEL,
  SELECT_MODEL_CHANNEL,
  isProviderAuthEvent,
  type PineModelCatalog,
  type ProviderLoginResult,
} from "./shared/models";
import {
  CREATE_PROJECT_CHANNEL,
  CLOSE_PROJECT_CHANNEL,
  DELETE_PROJECT_CHANNEL,
  LIST_PROJECTS_CHANNEL,
  OPEN_PROJECT_CHANNEL,
  PICK_PROJECT_FOLDERS_CHANNEL,
  PROJECTS_DIRECTORY,
  PROJECT_ATTACHMENTS_DIRECTORY,
  UPDATE_PROJECT_CHANNEL,
  type DeleteProjectResult,
  type ListProjectsResult,
  type PickProjectFoldersResult,
  type ProjectResult,
} from "./shared/projects";
import {
  DELETE_SESSION_CHANNEL,
  LOAD_SESSION_MESSAGES_CHANNEL,
  RENAME_SESSION_CHANNEL,
  RESUME_SESSION_CHANNEL,
  SEARCH_SESSIONS_CHANNEL,
  type DeleteSessionResult,
  type LoadSessionMessagesResult,
  type RenameSessionResult,
  type ResumeSessionResult,
  type SearchSessionsResult,
} from "./shared/sessions";
import {
  PROJECT_FILE_OPERATION_CHANNEL,
  PROJECT_FILE_ATTACHMENTS_CHANNEL,
  LIST_PROJECT_DIRECTORY_CHANNEL,
  READ_PROJECT_FILE_PREVIEW_CHANNEL,
  PROJECT_MEDIA_PROTOCOL,
  type ListProjectDirectoryResult,
} from "./shared/projectFiles";
import {
  OPAQUE_WINDOW_BACKGROUND,
  SET_SIDEBAR_VIBRANCY_CHANNEL,
  CLOSE_WINDOW_CHANNEL,
  TRANSPARENT_WINDOW_BACKGROUND,
  type SetSidebarVibrancyResult,
} from "./shared/window";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (started) {
  app.quit();
}

// Must run before app ready. The attachment image protocol lets the renderer
// display local images without granting it general filesystem access.
protocol.registerSchemesAsPrivileged([
  {
    privileges: {
      standard: true,
      secure: true,
      stream: true,
      supportFetchAPI: true,
    },
    scheme: PROJECT_MEDIA_PROTOCOL,
  },
  {
    privileges: { standard: true, stream: true, supportFetchAPI: true },
    scheme: ATTACHMENT_IMAGE_PROTOCOL,
  },
]);

const ATTACHMENT_IMAGE_CONTENT_TYPES: Record<string, string> = {
  avif: "image/avif",
  gif: "image/gif",
  jpeg: "image/jpeg",
  jpg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
};
const PROJECT_ID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const MAX_PASTED_ATTACHMENT_NAME_LENGTH = 200;

const SavePastedAttachmentRequestSchema = z.object({
  bytes: z
    .instanceof(Uint8Array)
    .refine(
      (bytes) =>
        bytes.byteLength > 0 && bytes.byteLength <= MAX_PASTED_IMAGE_BYTES,
    ),
  mimeType: z.enum(PASTED_IMAGE_MIME_TYPES),
  name: z.string().max(MAX_PASTED_ATTACHMENT_NAME_LENGTH).optional(),
});

/** Root of the Pine-managed projects tree; set once the app is ready. */
let projectsRootPath: string | null = null;

/**
 * Filesystem paths the user explicitly selected as message attachments, per
 * window. Previewing them mirrors the agent's read-only grant for the same
 * paths, so the protocol may serve them even outside granted folders.
 */
const attachedPreviewPaths = new Map<number, Set<string>>();

function registerAttachmentPreviewPaths(
  webContentsId: number,
  attachmentPaths: readonly string[],
): void {
  const registered = attachedPreviewPaths.get(webContentsId) ?? new Set();
  for (const attachmentPath of attachmentPaths) {
    registered.add(path.resolve(attachmentPath));
  }
  attachedPreviewPaths.set(webContentsId, registered);
}

/**
 * Whether the protocol may serve this file: either a Pine-managed pasted
 * attachment (`<projectsRoot>/<projectId>/attachments/<file>`) or a file
 * inside a folder granted to one of the currently open projects.
 */
function isServableAttachmentPath(resolvedPath: string): boolean {
  if (!projectsRootPath) return false;

  const relativePath = path.relative(projectsRootPath, resolvedPath);
  if (
    relativePath !== "" &&
    !relativePath.startsWith(`..${path.sep}`) &&
    relativePath !== ".." &&
    !path.isAbsolute(relativePath)
  ) {
    const segments = relativePath.split(path.sep);
    if (
      segments.length === 3 &&
      segments[1] === PROJECT_ATTACHMENTS_DIRECTORY &&
      PROJECT_ID_PATTERN.test(segments[0])
    ) {
      return true;
    }
  }
  if (getProjectRuntimes().isInsideGrantedFolder(resolvedPath)) {
    return true;
  }
  for (const registered of attachedPreviewPaths.values()) {
    if (registered.has(resolvedPath)) return true;
  }
  return false;
}

function registerAttachmentImageProtocol(): void {
  protocol.handle(ATTACHMENT_IMAGE_PROTOCOL, async (request) => {
    let requestedPath: string | null;
    try {
      requestedPath = new URL(request.url).searchParams.get("p");
    } catch {
      return new Response("Bad request", { status: 400 });
    }
    if (!requestedPath) {
      return new Response("Bad request", { status: 400 });
    }
    const resolvedPath = path.resolve(requestedPath);
    if (!isServableAttachmentPath(resolvedPath)) {
      return new Response("Forbidden", { status: 403 });
    }
    try {
      const contents = await readFile(resolvedPath);
      const extension = path.extname(resolvedPath).slice(1).toLowerCase();
      return new Response(contents, {
        headers: {
          "content-type":
            ATTACHMENT_IMAGE_CONTENT_TYPES[extension] ??
            "application/octet-stream",
        },
      });
    } catch {
      return new Response("Not found", { status: 404 });
    }
  });
}

nativeTheme.themeSource = "system";

let agentHost: AgentProcessHost | null = null;
const modelRecommendations = new ModelRecommendationService();
let projectRuntimes: ProjectRuntimeRegistry | null = null;
let projectRepository: ProjectRepository | null = null;

const ProjectFolderInputSchema = z.object({
  access: z.enum(["read-only", "read-write"]),
  id: z.uuid(),
  name: z.string().trim().min(1).max(100),
  path: z.string().min(1).max(4_096),
});
const ProjectMutationSchema = z
  .object({
    defaultFolderId: z.uuid(),
    folders: z.array(ProjectFolderInputSchema).min(1),
    name: z.string().trim().min(1).max(100),
  })
  .superRefine((project, context) => {
    const defaultFolder = project.folders.find(
      (folder) => folder.id === project.defaultFolderId,
    );
    if (defaultFolder?.access === "read-write") return;

    context.addIssue({
      code: "custom",
      message: "The default folder must have read-write access.",
      path: ["defaultFolderId"],
    });
  });
const PickProjectFoldersRequestSchema = z.object({
  mode: z.enum(["context", "default"]),
});
const ProjectIdRequestSchema = z.object({ id: z.uuid() });
const ProjectFilePreviewRequestSchema = ProjectEntryReferenceSchema.extend({
  projectId: z.uuid(),
});

async function previewPath(ownerId: number, request: unknown): Promise<string> {
  const entry = ProjectFilePreviewRequestSchema.parse(request);
  if (!getProjectRuntimes().isOpen(ownerId, entry.projectId))
    throw new Error("Project is no longer open.");
  const [filePath] = await getProjectRuntimes().projectEntryPaths(ownerId, [
    entry,
  ]);
  if (!getProjectRuntimes().isOpen(ownerId, entry.projectId))
    throw new Error("Project is no longer open.");
  return filePath;
}

function registerProjectMediaProtocol(): void {
  protocol.handle(PROJECT_MEDIA_PROTOCOL, async (request) => {
    try {
      const url = new URL(request.url);
      if (url.hostname !== "preview")
        return new Response(null, { status: 400 });
      const ownerId = z.coerce
        .number()
        .int()
        .positive()
        .parse(url.searchParams.get("owner"));
      const filePath = await previewPath(
        ownerId,
        Object.fromEntries(url.searchParams),
      );
      return await serveProjectMedia(request, filePath);
    } catch {
      return new Response(null, { status: 404 });
    }
  });
}
const UpdateProjectRequestSchema = ProjectMutationSchema.safeExtend({
  id: z.uuid(),
});
const SearchSessionsRequestSchema = z.object({
  query: z.string().max(500),
});
const SessionIdRequestSchema = z.object({
  sessionId: z.uuid(),
});
const RenameSessionRequestSchema = SessionIdRequestSchema.extend({
  name: z.string().trim().min(1).max(200),
});
const LoadSessionMessagesRequestSchema = z.object({
  // Pi entry cursors are opaque IDs: normally 8 hex characters, with a full
  // UUID only as a collision fallback.
  before: z.string().min(1).max(128).optional(),
  limit: z.number().int().min(1).max(100).optional(),
  sessionId: z.uuid(),
});
const PromptSessionRequestSchema = z.object({
  message: z.string().trim().min(1).max(100_000),
  target: z.discriminatedUnion("kind", [
    z.object({ kind: z.literal("new") }),
    z.object({ kind: z.literal("session"), sessionId: z.uuid() }),
  ]),
  streamingBehavior: z.enum(["follow-up", "steer"]).optional(),
  approvalMode: z.enum(["let-me-review", "auto-approve", "YOLO"]).optional(),
});
const RespondApprovalRequestSchema = z.object({
  requestId: z.uuid(),
  action: z.enum(["approve", "reject", "guide"]),
  guidance: z.string().trim().min(1).max(10_000).optional(),
});
const SetApprovalModeRequestSchema = z.object({
  approvalMode: z.enum(["let-me-review", "auto-approve", "YOLO"]),
});
const LoginProviderRequestSchema = z.object({
  authType: z.enum(["api_key", "oauth"]),
  loginId: z.uuid(),
  providerId: z.string().trim().min(1).max(200),
});
const ProviderAuthResponseRequestSchema = z.object({
  loginId: z.uuid(),
  promptId: z.uuid(),
  value: z.string().max(100_000),
});
const ProviderAuthLoginIdSchema = z.object({ loginId: z.uuid() });
const ProviderIdSchema = z.object({
  providerId: z.string().trim().min(1).max(200),
});
const SelectModelRequestSchema = z.object({
  modelId: z.string().trim().min(1).max(500),
  providerId: z.string().trim().min(1).max(200),
  thinkingLevel: z.enum([
    "off",
    "minimal",
    "low",
    "medium",
    "high",
    "xhigh",
    "max",
  ]),
});
const ProviderAuthUrlSchema = z.url().refine((url) => {
  try {
    return ["http:", "https:"].includes(new URL(url).protocol);
  } catch {
    return false;
  }
});
const ListProjectDirectoryRequestSchema = z.object({
  folderId: z.uuid(),
  relativePath: z.string().max(4_096),
});
const SetSidebarVibrancyRequestSchema = z.object({
  enabled: z.boolean(),
});
const InspectAttachmentsRequestSchema = z.object({
  paths: z.array(z.string().min(1).max(4_096)).max(100),
});
const OpenAttachmentRequestSchema = z.object({
  path: z
    .string()
    .min(1)
    .max(4_096)
    .refine((attachmentPath) => path.isAbsolute(attachmentPath)),
});

async function inspectAttachmentPaths(
  filePaths: readonly string[],
): Promise<PickAttachmentsResult> {
  const attachments = await Promise.all(
    filePaths.map(async (filePath): Promise<PineAttachment | undefined> => {
      const metadata = await stat(filePath);
      let kind: PineAttachmentKind;
      if (metadata.isFile()) kind = "file";
      else if (metadata.isDirectory()) kind = "directory";
      else return undefined;
      return {
        extension:
          kind === "file" ? path.extname(filePath).slice(1).toLowerCase() : "",
        kind,
        modifiedAt: metadata.mtime.toISOString(),
        name: path.basename(filePath),
        path: filePath,
        size: metadata.size,
      };
    }),
  );
  return {
    attachments: attachments.filter((attachment) => attachment !== undefined),
  };
}

function getProjectRepository(): ProjectRepository {
  if (!projectRepository) throw new Error("Project storage is not ready.");
  return projectRepository;
}

function getProjectRuntimes(): ProjectRuntimeRegistry {
  if (!projectRuntimes) throw new Error("Project runtime is not ready.");
  return projectRuntimes;
}

/** macOS dock bounce id for the pending approval attention request. */
let approvalBounceId: number | null = null;

/**
 * Surface a pending approval at the OS level: the dock icon bounces on
 * macOS and the taskbar button flashes on Windows until the decision (or
 * window focus) clears it.
 */
function requestApprovalAttention(ownerId: number): void {
  if (process.platform === "darwin") {
    approvalBounceId = app.dock?.bounce("informational") ?? null;
    return;
  }
  if (process.platform === "win32") {
    const sender = webContents.fromId(ownerId);
    const window = sender ? BrowserWindow.fromWebContents(sender) : undefined;
    window?.flashFrame(true);
  }
}

function clearApprovalAttention(): void {
  if (process.platform === "darwin") {
    if (approvalBounceId !== null) app.dock?.cancelBounce(approvalBounceId);
    approvalBounceId = null;
    return;
  }
  if (process.platform === "win32") {
    for (const window of BrowserWindow.getAllWindows()) {
      window.flashFrame(false);
    }
  }
}

const appIconPath = app.isPackaged
  ? path.join(process.resourcesPath, "icon.png")
  : path.join(app.getAppPath(), "resources/icon.png");

const createWindow = () => {
  const mainWindow = new BrowserWindow({
    title: "Pine",
    icon: appIconPath,
    titleBarStyle: "hidden",
    ...(process.platform === "darwin"
      ? { trafficLightPosition: { x: 21, y: 21 } }
      : { titleBarOverlay: true }),
    width: 1120,
    height: 840,
    minWidth: 720,
    minHeight: 540,
    show: false,
    autoHideMenuBar: process.platform !== "darwin",
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
      scrollBounce: true,
      preload: path.join(__dirname, "preload.js"),
    },
  });
  const webContentsId = mainWindow.webContents.id;
  installWindowShortcuts(mainWindow.webContents);

  // Focus stops the approval attention request (Windows flashes until the
  // window is focused; macOS bounces until the app activates).
  mainWindow.on("focus", clearApprovalAttention);

  mainWindow.once("ready-to-show", () => {
    mainWindow.show();
  });
  mainWindow.webContents.once("destroyed", () => {
    attachedPreviewPaths.delete(webContentsId);
    void projectRuntimes?.dispose(webContentsId);
  });
  mainWindow.webContents.setWindowOpenHandler(() => ({ action: "deny" }));

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    void mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    void mainWindow.loadFile(
      path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`),
    );
  }

  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.webContents.openDevTools();
  }
};

ipcMain.handle(CLOSE_WINDOW_CHANNEL, (event): void => {
  BrowserWindow.fromWebContents(event.sender)?.close();
});

ipcMain.handle(
  READ_PROJECT_FILE_PREVIEW_CHANNEL,
  async (event, request: unknown) => {
    const entry = ProjectFilePreviewRequestSchema.parse(request);
    const filePath = await previewPath(event.sender.id, entry);
    const url = new URL(`${PROJECT_MEDIA_PROTOCOL}://preview/`);
    url.search = new URLSearchParams({
      ...entry,
      owner: String(event.sender.id),
    }).toString();
    return readProjectFilePreview(filePath, url.href);
  },
);

ipcMain.handle(
  LIST_PROJECTS_CHANNEL,
  async (): Promise<ListProjectsResult> => ({
    projects: await getProjectRepository().list(),
  }),
);

ipcMain.handle(
  GET_MODEL_CATALOG_CHANNEL,
  async (): Promise<PineModelCatalog> => {
    const [catalog, recommendedIds] = await Promise.all([
      getProjectRuntimes().getModelCatalog(),
      modelRecommendations.get(),
    ]);
    const availableIds = new Set(catalog.models.map((model) => model.id));
    return {
      ...catalog,
      recommendedModelIds: recommendedIds.filter((id) => availableIds.has(id)),
    };
  },
);

const providerLoginOwners = new Map<string, number>();

ipcMain.handle(
  LOGIN_PROVIDER_CHANNEL,
  async (event, request: unknown): Promise<ProviderLoginResult> => {
    const parsed = LoginProviderRequestSchema.parse(request);
    providerLoginOwners.set(parsed.loginId, event.sender.id);
    try {
      return await getProjectRuntimes().loginProvider(parsed);
    } finally {
      providerLoginOwners.delete(parsed.loginId);
    }
  },
);

ipcMain.handle(
  RESPOND_PROVIDER_AUTH_CHANNEL,
  (event, request: unknown): Promise<{ accepted: boolean }> => {
    const parsed = ProviderAuthResponseRequestSchema.parse(request);
    if (providerLoginOwners.get(parsed.loginId) !== event.sender.id) {
      throw new Error("Provider login does not belong to this window.");
    }
    return getProjectRuntimes().respondToProviderAuth(
      parsed.loginId,
      parsed.promptId,
      parsed.value,
    );
  },
);

ipcMain.handle(
  CANCEL_PROVIDER_AUTH_CHANNEL,
  (event, request: unknown): Promise<{ cancelled: boolean }> => {
    const { loginId } = ProviderAuthLoginIdSchema.parse(request);
    if (providerLoginOwners.get(loginId) !== event.sender.id) {
      throw new Error("Provider login does not belong to this window.");
    }
    return getProjectRuntimes().cancelProviderAuth(loginId);
  },
);

ipcMain.handle(
  LOGOUT_PROVIDER_CHANNEL,
  (_event, request: unknown): Promise<{ disposed: boolean }> =>
    getProjectRuntimes().logoutProvider(
      ProviderIdSchema.parse(request).providerId,
    ),
);

ipcMain.handle(
  SELECT_MODEL_CHANNEL,
  (event, request: unknown): Promise<{ disposed: boolean }> =>
    getProjectRuntimes().selectModel(
      event.sender.id,
      SelectModelRequestSchema.parse(request),
    ),
);

ipcMain.handle(OPEN_PROVIDER_AUTH_URL_CHANNEL, async (_event, url: unknown) => {
  await shell.openExternal(ProviderAuthUrlSchema.parse(url));
});

ipcMain.handle(
  PICK_ATTACHMENTS_CHANNEL,
  async (event): Promise<PickAttachmentsResult> => {
    const parentWindow = BrowserWindow.fromWebContents(event.sender);
    const options: OpenDialogOptions = {
      title: "Add Attachments",
      buttonLabel: "Add",
      properties: ["openFile", "multiSelections"],
    };
    const selection = parentWindow
      ? await dialog.showOpenDialog(parentWindow, options)
      : await dialog.showOpenDialog(options);

    if (selection.canceled) return { attachments: [] };
    const result = await inspectAttachmentPaths(selection.filePaths);
    registerAttachmentPreviewPaths(
      event.sender.id,
      result.attachments.map((attachment) => attachment.path),
    );
    return result;
  },
);

ipcMain.handle(
  PICK_ATTACHMENT_FOLDERS_CHANNEL,
  async (event): Promise<PickAttachmentsResult> => {
    const parentWindow = BrowserWindow.fromWebContents(event.sender);
    const options: OpenDialogOptions = {
      title: "Add Attachment Folders",
      buttonLabel: "Add",
      properties: ["openDirectory", "multiSelections"],
    };
    const selection = parentWindow
      ? await dialog.showOpenDialog(parentWindow, options)
      : await dialog.showOpenDialog(options);

    if (selection.canceled) return { attachments: [] };
    const result = await inspectAttachmentPaths(selection.filePaths);
    registerAttachmentPreviewPaths(
      event.sender.id,
      result.attachments.map((attachment) => attachment.path),
    );
    return result;
  },
);

ipcMain.handle(
  INSPECT_ATTACHMENTS_CHANNEL,
  async (event, request: unknown): Promise<PickAttachmentsResult> => {
    const { paths } = InspectAttachmentsRequestSchema.parse(request);
    const result = await inspectAttachmentPaths(paths);
    registerAttachmentPreviewPaths(
      event.sender.id,
      result.attachments.map((attachment) => attachment.path),
    );
    return result;
  },
);

ipcMain.handle(
  OPEN_ATTACHMENT_CHANNEL,
  async (_event, request: unknown): Promise<OpenAttachmentResult> => {
    const { path: attachmentPath } = OpenAttachmentRequestSchema.parse(request);
    const metadata = await stat(attachmentPath);
    if (!metadata.isFile() && !metadata.isDirectory()) {
      return { opened: false, error: "Attachment is not a file or folder." };
    }
    const error = await shell.openPath(attachmentPath);
    return error ? { opened: false, error } : { opened: true };
  },
);

ipcMain.handle(
  SAVE_PASTED_ATTACHMENT_CHANNEL,
  async (event, request: unknown): Promise<SavePastedAttachmentResult> => {
    const parsed = SavePastedAttachmentRequestSchema.parse(request);
    const attachmentsRoot = getProjectRuntimes().attachmentsRootFor(
      event.sender.id,
    );
    if (!attachmentsRoot) {
      throw new Error("No project is open in this window.");
    }

    const extension = extensionForPastedImage(parsed.mimeType);
    const displayName =
      path
        .basename(parsed.name ?? "")
        .trim()
        .slice(0, 200) || `image.${extension}`;

    await mkdir(attachmentsRoot, { recursive: true });
    const attachmentPath = path.join(
      attachmentsRoot,
      `${randomUUID()}.${extension}`,
    );
    await writeFile(attachmentPath, parsed.bytes);
    const metadata = await stat(attachmentPath);

    const attachment: PineAttachment = {
      extension,
      kind: "file",
      modifiedAt: metadata.mtime.toISOString(),
      name: displayName,
      path: attachmentPath,
      size: metadata.size,
    };
    registerAttachmentPreviewPaths(event.sender.id, [attachmentPath]);
    return { attachment };
  },
);

ipcMain.handle(
  PICK_PROJECT_FOLDERS_CHANNEL,
  async (event, request: unknown): Promise<PickProjectFoldersResult> => {
    const { mode } = PickProjectFoldersRequestSchema.parse(request);
    const parentWindow = BrowserWindow.fromWebContents(event.sender);
    const options: OpenDialogOptions = {
      title:
        mode === "default" ? "Choose Default Folder" : "Add Context Folders",
      buttonLabel: mode === "default" ? "Choose" : "Add",
      properties: [
        "openDirectory",
        ...(mode === "context" ? (["multiSelections"] as const) : []),
        "createDirectory",
        "promptToCreate",
      ],
    };
    const selection = parentWindow
      ? await dialog.showOpenDialog(parentWindow, options)
      : await dialog.showOpenDialog(options);

    if (selection.canceled) return { folders: [] };
    return {
      folders: selection.filePaths.map((folderPath) => ({
        access: "read-write",
        id: randomUUID(),
        name: path.basename(folderPath),
        path: folderPath,
      })),
    };
  },
);

ipcMain.handle(
  CREATE_PROJECT_CHANNEL,
  async (_event, request: unknown): Promise<ProjectResult> => ({
    project: await getProjectRepository().create(
      ProjectMutationSchema.parse(request),
    ),
  }),
);

ipcMain.handle(CLOSE_PROJECT_CHANNEL, async (event): Promise<void> => {
  await getProjectRuntimes().dispose(event.sender.id);
});

ipcMain.handle(
  OPEN_PROJECT_CHANNEL,
  async (event, request: unknown): Promise<ProjectResult> => {
    const { id } = ProjectIdRequestSchema.parse(request);
    const repository = getProjectRepository();
    const project = await repository.open(id);
    await getProjectRuntimes().open(
      event.sender.id,
      project,
      repository.dataPaths(id),
    );
    return { project };
  },
);

ipcMain.handle(
  UPDATE_PROJECT_CHANNEL,
  async (event, request: unknown): Promise<ProjectResult> => {
    const { id, ...input } = UpdateProjectRequestSchema.parse(request);
    const repository = getProjectRepository();
    const project = await repository.update(id, input);
    if (getProjectRuntimes().isOpen(event.sender.id, id)) {
      await getProjectRuntimes().open(
        event.sender.id,
        project,
        repository.dataPaths(id),
      );
    }
    return { project };
  },
);

ipcMain.handle(
  DELETE_PROJECT_CHANNEL,
  async (event, request: unknown): Promise<DeleteProjectResult> => {
    const { id } = ProjectIdRequestSchema.parse(request);
    if (getProjectRuntimes().isOpen(event.sender.id, id)) {
      await getProjectRuntimes().dispose(event.sender.id);
    }
    return { deleted: await getProjectRepository().delete(id) };
  },
);

// Serialize filesystem operations so concurrent drags cannot overwrite one another.
let projectFileOperationQueue: Promise<void> = Promise.resolve();
ipcMain.handle(PROJECT_FILE_OPERATION_CHANNEL, (event, request: unknown) => {
  const operation = ProjectFileOperationSchema.parse(request);
  const pending = projectFileOperationQueue.then(() =>
    getProjectRuntimes().operateFile(event.sender.id, operation, {
      trash: (filePath) => shell.trashItem(filePath),
      open: (filePath) => shell.openPath(filePath),
      reveal: (filePath) => shell.showItemInFolder(filePath),
      copyPath: (filePath) => clipboard.writeText(filePath),
    }),
  );
  projectFileOperationQueue = pending.catch(() => undefined);
  return pending;
});

ipcMain.handle(
  PROJECT_FILE_ATTACHMENTS_CHANNEL,
  async (event, request: unknown): Promise<PickAttachmentsResult> => {
    const entries = z
      .array(ProjectEntryReferenceSchema)
      .min(1)
      .max(100)
      .parse(request);
    const paths = await getProjectRuntimes().projectEntryPaths(
      event.sender.id,
      entries,
    );
    const result = await inspectAttachmentPaths(paths);
    registerAttachmentPreviewPaths(
      event.sender.id,
      result.attachments.map((attachment) => attachment.path),
    );
    return result;
  },
);

ipcMain.handle(
  LIST_PROJECT_DIRECTORY_CHANNEL,
  async (event, request: unknown): Promise<ListProjectDirectoryResult> => {
    const { folderId, relativePath } =
      ListProjectDirectoryRequestSchema.parse(request);
    return {
      entries: await getProjectRuntimes().listDirectory(
        event.sender.id,
        folderId,
        relativePath,
      ),
    };
  },
);

ipcMain.handle(
  SEARCH_SESSIONS_CHANNEL,
  async (event, request: unknown): Promise<SearchSessionsResult> => {
    const { query } = SearchSessionsRequestSchema.parse(request);
    return {
      sessions: await getProjectRuntimes().search(event.sender.id, query),
    };
  },
);

ipcMain.handle(
  RESUME_SESSION_CHANNEL,
  async (event, request: unknown): Promise<ResumeSessionResult> => {
    const { sessionId } = SessionIdRequestSchema.parse(request);
    return getProjectRuntimes().resume(event.sender.id, sessionId);
  },
);

ipcMain.handle(
  DELETE_SESSION_CHANNEL,
  async (event, request: unknown): Promise<DeleteSessionResult> => {
    const { sessionId } = SessionIdRequestSchema.parse(request);
    return {
      deleted: await getProjectRuntimes().deleteSession(
        event.sender.id,
        sessionId,
      ),
    };
  },
);

ipcMain.handle(
  RENAME_SESSION_CHANNEL,
  async (event, request: unknown): Promise<RenameSessionResult> => {
    const { name, sessionId } = RenameSessionRequestSchema.parse(request);
    return {
      session: await getProjectRuntimes().renameSession(
        event.sender.id,
        sessionId,
        name,
      ),
    };
  },
);

ipcMain.handle(
  LOAD_SESSION_MESSAGES_CHANNEL,
  async (event, request: unknown): Promise<LoadSessionMessagesResult> => {
    const { before, limit, sessionId } =
      LoadSessionMessagesRequestSchema.parse(request);
    return getProjectRuntimes().loadMessages(
      event.sender.id,
      sessionId,
      before,
      limit,
    );
  },
);

ipcMain.handle(
  PROMPT_SESSION_CHANNEL,
  async (event, request: unknown): Promise<PromptSessionResult> =>
    getProjectRuntimes().prompt(
      event.sender.id,
      PromptSessionRequestSchema.parse(request),
    ),
);

ipcMain.handle(
  ABORT_SESSION_CHANNEL,
  async (event): Promise<AbortSessionResult> =>
    getProjectRuntimes().abort(event.sender.id),
);

ipcMain.handle(
  SET_APPROVAL_MODE_CHANNEL,
  async (event, request: unknown): Promise<SetApprovalModeResult> => {
    const { approvalMode } = SetApprovalModeRequestSchema.parse(request);
    return getProjectRuntimes().setApprovalMode(event.sender.id, approvalMode);
  },
);

ipcMain.handle(
  APPROVAL_RESPONSE_CHANNEL,
  (event, request: unknown): { accepted: boolean } =>
    getProjectRuntimes().respondApproval(
      event.sender.id,
      RespondApprovalRequestSchema.parse(
        request,
      ) satisfies RespondApprovalRequest,
    ),
);

ipcMain.handle(
  SET_SIDEBAR_VIBRANCY_CHANNEL,
  (event, request: unknown): SetSidebarVibrancyResult => {
    const { enabled } = SetSidebarVibrancyRequestSchema.parse(request);
    if (process.platform !== "darwin") return { applied: false };

    const window = BrowserWindow.fromWebContents(event.sender);
    if (!window || window.isDestroyed()) return { applied: false };

    window.setVibrancy(enabled ? "sidebar" : null);
    // An opaque window background covers the native vibrancy material, so it
    // must become fully transparent while the effect is enabled.
    window.setBackgroundColor(
      enabled ? TRANSPARENT_WINDOW_BACKGROUND : OPAQUE_WINDOW_BACKGROUND,
    );
    return { applied: true };
  },
);

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  if (!app.isPackaged) app.dock?.setIcon(appIconPath);
  agentHost = AgentProcessHost.createDefault();
  projectsRootPath = path.join(app.getPath("userData"), PROJECTS_DIRECTORY);
  projectRepository = new ProjectRepository(projectsRootPath);
  registerAttachmentImageProtocol();
  registerProjectMediaProtocol();
  projectRuntimes = new ProjectRuntimeRegistry(
    agentHost,
    path.join(app.getPath("userData"), "agent"),
  );
  agentHost.subscribe((agentEvent) => {
    if (isProviderAuthEvent(agentEvent)) {
      const ownerId = providerLoginOwners.get(agentEvent.loginId);
      if (ownerId !== undefined) {
        webContents
          .fromId(ownerId)
          ?.send(PROVIDER_AUTH_EVENT_CHANNEL, agentEvent);
      }
      return;
    }
    const ownerId = projectRuntimes?.ownerOfSession(agentEvent.sessionId);
    if (ownerId === undefined) return;
    if (agentEvent.type === "context-usage") {
      projectRuntimes?.updateContextUsage(agentEvent.sessionId, {
        tokens: agentEvent.tokens,
        contextWindow: agentEvent.contextWindow,
        percent: agentEvent.percent,
        cost: agentEvent.cost,
      });
    } else if (agentEvent.type === "approval-request") {
      projectRuntimes?.trackApproval(agentEvent.requestId, ownerId);
      requestApprovalAttention(ownerId);
    } else if (agentEvent.type === "approval-decided") {
      projectRuntimes?.forgetApproval(agentEvent.requestId);
      clearApprovalAttention();
    }
    webContents.fromId(ownerId)?.send(SESSION_EVENT_CHANNEL, agentEvent);
  });
  createWindow();
});

app.on("will-quit", () => {
  void agentHost?.dispose();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
