import {
  app,
  BrowserWindow,
  dialog,
  ipcMain,
  nativeTheme,
  type OpenDialogOptions,
} from "electron";
import started from "electron-squirrel-startup";
import path from "node:path";
import { z } from "zod";
import { openWorkspace } from "./main/workspaces";
import { WorkspaceRuntimeRegistry } from "./main/workspaceRuntime";
import {
  OPEN_WORKSPACE_CHANNEL,
  type OpenWorkspaceResult,
} from "./shared/projects";
import {
  RESUME_SESSION_CHANNEL,
  SEARCH_SESSIONS_CHANNEL,
  type ResumeSessionResult,
  type SearchSessionsResult,
} from "./shared/sessions";
import {
  LIST_WORKSPACE_DIRECTORY_CHANNEL,
  type ListWorkspaceDirectoryResult,
} from "./shared/workspaceFiles";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (started) {
  app.quit();
}

nativeTheme.themeSource = "system";

const workspaceRuntimes = new WorkspaceRuntimeRegistry();
const SearchSessionsRequestSchema = z.object({
  query: z.string().max(500),
});
const ResumeSessionRequestSchema = z.object({
  sessionId: z.uuid(),
});
const ListWorkspaceDirectoryRequestSchema = z.object({
  relativePath: z.string().max(4_096),
});

const createWindow = () => {
  const mainWindow = new BrowserWindow({
    title: "Pine",
    titleBarStyle: "hidden",
    ...(process.platform === "darwin"
      ? { trafficLightPosition: { x: 21, y: 21 } }
      : { titleBarOverlay: true }),
    width: 1120,
    height: 760,
    minWidth: 720,
    minHeight: 540,
    show: false,
    autoHideMenuBar: process.platform !== "darwin",
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
      preload: path.join(__dirname, "preload.js"),
    },
  });
  const webContentsId = mainWindow.webContents.id;

  mainWindow.once("ready-to-show", () => {
    mainWindow.show();
  });
  mainWindow.webContents.once("destroyed", () => {
    void workspaceRuntimes.dispose(webContentsId);
  });

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    void mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    void mainWindow.loadFile(
      path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`),
    );
  }

  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.webContents.openDevTools();
  }
};

ipcMain.handle(
  OPEN_WORKSPACE_CHANNEL,
  async (event): Promise<OpenWorkspaceResult> => {
    const parentWindow = BrowserWindow.fromWebContents(event.sender);
    const options: OpenDialogOptions = {
      title: "Open Folder",
      buttonLabel: "Open",
      properties: ["openDirectory", "createDirectory", "promptToCreate"],
    };
    const selection = parentWindow
      ? await dialog.showOpenDialog(parentWindow, options)
      : await dialog.showOpenDialog(options);

    if (selection.canceled || selection.filePaths.length === 0) {
      return { workspace: null };
    }

    const workspace = await openWorkspace(selection.filePaths[0]);
    await workspaceRuntimes.open(event.sender.id, workspace);
    return { workspace };
  },
);

ipcMain.handle(
  LIST_WORKSPACE_DIRECTORY_CHANNEL,
  async (event, request: unknown): Promise<ListWorkspaceDirectoryResult> => {
    const { relativePath } = ListWorkspaceDirectoryRequestSchema.parse(request);
    return {
      entries: await workspaceRuntimes.listDirectory(
        event.sender.id,
        relativePath,
      ),
    };
  },
);

ipcMain.handle(
  SEARCH_SESSIONS_CHANNEL,
  async (event, request: unknown): Promise<SearchSessionsResult> => {
    const { query } = SearchSessionsRequestSchema.parse(request);
    return {
      sessions: await workspaceRuntimes.search(event.sender.id, query),
    };
  },
);

ipcMain.handle(
  RESUME_SESSION_CHANNEL,
  async (event, request: unknown): Promise<ResumeSessionResult> => {
    const { sessionId } = ResumeSessionRequestSchema.parse(request);
    return {
      session: await workspaceRuntimes.resume(event.sender.id, sessionId),
    };
  },
);

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
